channels:
  - conda-forge
  - bioconda
  - nvidia
dependencies:
  - conda-forge::python==3.10.*
  - conda-forge::pip
  - nvidia::cudatoolkit==11.6.*
  - bioconda::mmseqs2
  - bioconda::foldseek
  - pip:
      - biopython
      - scikit-learn
      - datasets
      - torch
      - matplotlib
      - numpy
      - scipy
      - seaborn
      - transformers
      - cchardet
